### ISSUE TITLE
Bug: Local Path Definition

### ISSUE THREAD

**Issue by jsimonclark** [Battery-Intelligence-Lab/multiscale-coupling#2]
**Bug:** the path definition in Battery_model.m is hard coded as the local path on the developer's machine (C:\Users\Jie\Desktop\Github)

**Possible Solution:** you can make this more generic by defining a path variable that identifies the actual location of the folder on the user's system. You might try calling either pwd() or mfilename('fullpath') from within Battery_model.m

**Comment by davidhowey** [comment]
thanks @jsimonclark - appreciated. have updated the code:
```
localpath = pwd();
model.modelPath(localpath);
```

**Comment by davidhowey** [comment]
thanks @jsimonclark - appreciated. have updated the code:
```
localpath = pwd();
model.modelPath(localpath);
```
